export function getPlayerDom() {
  return {
    audioElement: document.getElementById('audioElement'),
    fileInput: document.getElementById('dir'),
    listEl: document.getElementById('playlist'),
    trackTitleEl: document.getElementById('trackTitle'),
    trackArtistEl: document.getElementById('trackArtist'),
    trackArtworkEl: document.getElementById('trackArtwork'),
    trackAdjusterButtonsEl: document.getElementById('trackAdjusterButtons'),
    trackStartToggleEl: document.getElementById('trackStartToggle'),
    trackGainToggleEl: document.getElementById('trackGainToggle'),
    trackStartDefaultBtnEl: document.getElementById('trackStartDefaultBtn'),
    trackGainDefaultBtnEl: document.getElementById('trackGainDefaultBtn'),
    trackGainUnityBtnEl: document.getElementById('trackGainUnityBtn'),
    trackStartWheelEl: document.getElementById('trackStartWheel'),
    gainInfoEl: document.getElementById('gainInfo'),
    trackStartInfoEl: document.getElementById('trackStartInfo'),
    explicitTrackToggleEl: document.getElementById('explicitTrackToggle'),
    addAllBtn: document.getElementById('addAllBtn'),
    currentPlaylistNameEl: document.getElementById('currentPlaylistName'),
    playlistsEl: document.getElementById('playlists'),
    addPlaylistBtn: document.getElementById('addPlaylist'),
    explicitBtn: document.getElementById('explicitBtn'),
    shuffleBtn: document.getElementById('shuffleBtn'),
    normalizeBtn: document.getElementById('normalizeBtn'),
    clearCacheBtn: document.getElementById('clearCacheBtn'),
    screens: [
      document.getElementById('screen1'),
      document.getElementById('screen2'),
      document.getElementById('screen3'),
    ].filter(Boolean),
  };
}
