export function createPlayerState() {
  return {
    currentScreen: 1,
    touchStartX: 0,
    touchStartY: 0,
    touchActive: false,
    touchScrollable: null,
    index: 0,
    isPlaying: false,
    offset: 0,
    pendingStartOffset: null,
    playSequence: 0,
    pendingPlaySequence: 0,
    shuffle: false,
    normalize: false,
    files: [],
    playlists: [],
    currentPlaylistId: null,
    shuffledPlaylistItemsById: new Map(),
    fileIndexByKey: new Map(),
    isSettingSrc: false,
    isInternalTransition: false,
    audioContext: null,
    gainNode: null,
    audioSourceNode: null,
    currentObjectUrl: null,
    objectUrlsPendingRevoke: [],
    mediaSessionSignature: null,
  };
}
